language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
sudo: false
addons:
 apt:
  packages:
    - python-rdkit
    - librdkit1
    - rdkit-data
install:
  - pip install -r requirements/development.txt
script:
  - coverage run --source=molvs setup.py test
after_success:
  - coveralls
